### ISSUE TITLE
Duplicate entries in resume section

### ISSUE THREAD

**Issue by Minefield247** [wako-app/wako#182]
![Screenshot_20201010-152006](https://user-images.githubusercontent.com/34307802/95657589-2a793900-0b0d-11eb-87d3-5c3cdca5fc1a.jpg)
Any idea why I would be getting multiple episode entries in the resume section. This happens a lot. Sometimes there are only a couple of duplicates, sometimes more? I've only started this episode once, then paused it for a while, then stopped it using the app.

**Comment by JumBay** [comment]
It should be fixed in 4.5.2. You would have to clean your playlists first.

**Comment by Minefield247** [comment]
I'm on version 4.6 and am still getting duplicate entries in the resume section.
![Screenshot_20201027-210531](https://user-images.githubusercontent.com/34307802/97362498-0487be80-1899-11eb-881b-a5672f0189e4.jpg)
